### PR TITLE
Add the ability to set Unicon options globally.

### PR DESCRIPTION
**Pull request by themustafaomar**
Add the ability to customize the Unicon component options globally.
So we can now set the options like so:
```javascript
Vue.use(Unicon, {
  fill: '#414154',
  height: 15,
  width: 15,
})
```

### CODE REVIEW

**Comment by hmaesta** [comment]
Any update on this? Would be a really nice enhancement 🙌

**Comment by themustafaomar** [comment]
@antonreshetov Please take a look at the commit :(

**Comment by hmaesta** [comment]
Hey @antonreshetov – this PR is super simple and it's a _more-than-welcome_ feature, but it's waiting for a while.
Besides, I answered some issues but the remain open - but should be closed.

I am not in a position of asking something – since I am not paying for this great work –, but if you need some help managing PRs and issues, I am available to help 😃

**Comment by antonreshetov** [comment]
@hmaesta Apparently, the author has removed the PR branch. I've made a new PR #37, so this feature has been added and will be released in a new version.

**Pull request closed without merging**
